{{if .Values.ingress.enable}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cubefs-dashboard
spec:
  ingressClassName: {{.Values.ingress.ingressClassName}}
  rules:
  - host: {{.Values.ingress.hostname}}
    http:
      paths:
      - backend:
          service:
            name: cubefs-dashboard
            port:
              number: {{.Values.service.port}}
        path: /
        pathType: Prefix
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{.Values.ingress.hostname}}
    secretName: {{.Values.ingress.secretName}}
  {{- end}}
{{end}}
