apiVersion: v1
kind: Secret
metadata:
  name: cubefs-dashboard-mysql
type: Opaque
stringData:
  mysql.yaml: |
    mysql:
      host: localhost
      port: 3306
      database: {{.Values.mariadb.auth.database}}
      user: {{.Values.mariadb.auth.username}}
      password: {{.Values.mariadb.auth.password}}
      maxIdleConn: 20
      MaxOpenConn: 300
